[NM-920] Validate metadata
airdropgames/nft-marketplace-sdk pull request #12
Opened 2023-09-27 08:36 UTC by resaairdropped

Validate metadata
![image](https://github.com/airdropgames/nft-marketplace-sdk/assets/139849583/c3246d33-55d0-4d34-a3c6-0d1f9eaa490c)

2023-09-27 09:23 UTC, rashgaroth requested changes

2023-09-27 09:23 UTC, rashgaroth commented on src/apis/tenant/index.ts
> +  async validatadeUri(uri: string): Promise<Boolean> {
add try/catch wrapper

2023-09-27 09:23 UTC, rashgaroth commented on testScripts/checkMetadata.ts
> +
please also add the wrong metadata url case

2023-09-27 12:17 UTC, rashgaroth approved these changes

2023-10-04 07:25 UTC, capt4ce approved these changes

2023-10-04 07:25 UTC, merged